### ISSUE TITLE
`npm install serverless --save` でインストールするとpostinstall.jsでエラーになる

### ISSUE THREAD

**Issue by k1LoW** [serverless-japan/forum#1]
# This is a Bug Report

## Description

本来のインストール方法は `npm install serverless -g` だと思うのですが、これを `npm install serverless --save` でプロジェクト内にインストールするとpostinstall.jsでエラーになります。

postinstall.jsがautocompletionを設定するためにtabtabを実行する処理だということは理解しています。

その上で、どれが正しいのかがわかりません。

1. `npm install serverless --save` は想定していないのでサポート外（バグではない）
2. バグなのでpostinstall.jsが動くように直すべき
3. バグだが、 `npm install serverless --save` のときにはpostinstall.jsは動くべきではない（.zshrcを操作すべきではない）
4. 実は回避する方法がある

誰か教えてもらえませんでしょうか？

Similar or dependent issues:
* https://github.com/serverless/serverless/issues/3760
* https://github.com/serverless/serverless/pull/3763

## Additional Data

* ***Serverless Framework Version you're using***: 1.15.3
* ***Operating System***: macOS 10.11.6
* ***Stack Trace***:

```
> serverless@1.15.3 postinstall /Users/k1low/.ghq/github.com/faultline/faultline/node_modules/serverless
> node ./scripts/postinstall.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/k1low/.ghq/github.com/faultline/faultline/node_modules/serverless/node_modules/tabtab/src/cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/k1low/.ghq/github.com/faultline/faultline/node_modules/serverless/node_modules/tabtab/src/cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
```

* ***Provider Error messages***:

None

**Comment by horike37** [comment]
@k1LoW 
まだ、ロゴもない怪しい感じのフォーラムへ
初投稿ありがとうございますw

まだ、再現性等確認してないのでなんとも言えないのですが、
>npm install serverless --save は想定していないのでサポート外（バグではない）

現時点で言えることは、これはサポートされてます。

なので、解決策としては2 - 4のいずれかになるはずです。
僕の方でも一度再現性確認してみますね。

**Comment by k1LoW** [comment]
@horike37 ありがとうございます！

以下簡易再現方法です。

```sh
~ > node -v
v6.10.2
~ > mkdir -p tmp/slstest
~ > cd tmp/slstest
~/tmp/slstest > npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (slstest)
version: (1.0.0)
description:
entry point: (index.js)
test command:
git repository:
keywords:
license: (ISC) MIT
About to write to /Users/k1low/tmp/slstest/package.json:

{
  "name": "slstest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "k1LoW <k1lowxb@gmail.com> (https://github.com/k1LoW)",
  "license": "MIT"
}


Is this ok? (yes) yes
~/tmp/slstest > npm install serverless --save
npm WARN prefer global serverless@1.15.3 should be installed with -g

> spawn-sync@1.0.15 postinstall /Users/k1low/tmp/slstest/node_modules/spawn-sync
> node postinstall


> serverless@1.15.3 postinstall /Users/k1low/tmp/slstest/node_modules/serverless
> node ./scripts/postinstall.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/k1low/tmp/slstest/node_modules/serverless/node_modules/tabtab/src/cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/k1low/tmp/slstest/node_modules/serverless/node_modules/tabtab/src/cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
```

気になる点としては `npm WARN prefer global serverless@1.15.3 should be installed with -g` と怒られているところくらいでしょうか。

**Comment by horike37** [comment]
@k1LoW 
僕の環境でも再現しました。
結論をいうと「2. バグなのでpostinstall.jsが動くように直すべき」で、https://github.com/serverless/serverless/pull/3763 のPRで修正済みです。masterブランチの最新をcloneするとpostinstallは正しく動きました。

なので、次バージョンのリリース待ちですね。いつリリースされるのかはPR上で聞いてみました。
ちなみにこのエラーが起きてもServerless自体は正常にインストール完了しています。

このpostinstall内でコマンドのオートコンプリートの設定をしているので、このエラーの弊害としてはオートコンプリートの機能が使えないということです。通常のsls deployなどの機能には影響がないので、リリースまではこのエラーを無視して使うで良いと思います。

**Comment by k1LoW** [comment]
@horike37 おお！ありがとうございます！

> ちなみにこのエラーが起きてもServerless自体は正常にインストール完了しています。

はい。そこまでは追っていて（PATH解決がうまくいっていないだけ）、手元では使っているのですが、エラーがでるのはちょっと心象的によくないなと思っていました。

ありがとうございます！

**Comment by k1LoW** [comment]
リリースされたらcloseしますかね

**Comment by horike37** [comment]
あ、ちょっと勘違いしてました。serverless/serverless#3763 は、https://github.com/serverless/serverless/releases/tag/v1.15.2 にてリリースされてますね。。
なら別の原因があるのかも。

**Comment by k1LoW** [comment]
> 僕の環境でも再現しました。

> masterブランチの最新をcloneするとpostinstallは正しく動きました。

ということは確かに何かありますね。。。なんにしてもmasterでうごくということは待てば解決されそうですね！

**Comment by horike37** [comment]
masterでも解決してない気がしますね。。ソース見る感じだと。
グローバルインストールの時しか考慮されてないのかも。もうちょっと詳しく見てみます。

**Comment by k1LoW** [comment]
グローバルインストールの時はグローバルインストールされているディレクトリの

```
/serverless/node_modules/tabtab/src/cli.js
```

を見ているのでファイルを見つけて実行できるのですが、serverlessを`--save` でいれるとネストされて

```
./node_modules/serverless/node_modules/tabtab/src/cli.js
```

を探そうとします。しかし、実際は

```
./node_modules/tabtab/src/cli.js
```

にtabtabがインストールされているのでアウト　という感じですね。

**Comment by horike37** [comment]
https://github.com/serverless/serverless/issues/3792
issue立てました。ローカルインストールでエラー吐かれると、faultlineのように内部的にslsを使ってるプロジェクトは困りますね。。

**Comment by k1LoW** [comment]
ありがとうございます！本家をwatchしていきます

**Comment by horike37** [comment]
bugとhelp wantedのタグが付いたので、バグなのでプルリク待ちのステータスになりました。

@k1LoW プルリクやってみます？
やらないなら、僕パッチ作ってプルリクしちゃいますが。

**Comment by k1LoW** [comment]
@horike37 
https://github.com/serverless/serverless/pull/3798 で出してみましたー

**Comment by k1LoW** [comment]
@horike37 援護射撃ざっす！ https://github.com/serverless/serverless/pull/3798#issuecomment-310023751

**Comment by horike37** [comment]
集団戦法！
ソースめっちゃシンプルになりましたね！`require.resolve`は知らなかった。
https://github.com/serverless/serverless/pull/3798/commits/e68450f5b54e8f3d8d48f4690159efc257ed413f

**Comment by k1LoW** [comment]
1.17のマイルストーンがついた！

**Comment by k1LoW** [comment]
無事マージされました！ので本件Closeします。

@horike37 ありがとうございました！

**Comment by horike37** [comment]
グッジョブ！！@k1LoW
:thumbsup::thumbsup::thumbsup::thumbsup::thumbsup::thumbsup::thumbsup::thumbsup:
