### ISSUE TITLE
Serverless Frameworkでserverless.ymlが解釈される前のlifecycle eventってありますか？

### ISSUE THREAD

**Issue by k1LoW** [serverless-japan/forum#3]
### モチベーション

YAMLをJSオブジェクトとして読み込んだ段階のserverless.ymlをいじりたいです。

具体的には `file(./config.yml)` などの設定で、config.ymlが存在しなくてもエラーにならずにデプロイをすすめたいのです。

> なさそうですが。。

**Comment by k1LoW** [comment]
https://github.com/serverless/serverless/blob/master/lib/classes/Service.js#L64 で解釈されてますね。。。

**Comment by k1LoW** [comment]
> 具体的には file(./config.yml) などの設定で、config.ymlが存在しなくてもエラーにならずにデプロイをすすめたいのです。

すみません。上記はServerless Frameworkのバージョンをあげたら求める形になりました。

よってCloseします。

**Comment by horike37** [comment]
https://github.com/serverless/serverless/pull/4448
ああー、多分ここで対応されたやつっすね。

**Comment by k1LoW** [comment]
@horike37 さすがです！さすがdirty hands man！全てを見ている！
