### ISSUE TITLE
functionsのファイル読み込みについて

### ISSUE THREAD

**Issue by sueken5** [serverless-japan/forum#6]
初めまして、sueken5と言います。よろしくお願いします。

functionsについての質問です。

公式のdocmentには以下のような記述に対応しているとあるのですが、このように書くと
```
# serverless.yml
...

functions:
  - ${file(../foo-functions.yml)}
  - ${file(../bar-functions.yml)}
```

```
Missing "handler" property in function "0". Please make sure you point to the correct lambda handler. For example: handler.hello. Please check the docs for more info
```

というエラーが出てしまいます。どうしたら良いのでしょうか？よろしくお願いします。

**Comment by horike37** [comment]
@sueken5 
はじめまして！ようこそ！

あー、この配列でfunctionを指定する機能は、次のバージョン1.27.0でリリースされる機能なんです。なので今は使えません。

これServerless.comの仕組みがあまり良くなくて、documentはmasterブランチにマージされた時点で公開されちゃうんですよね。ただ、リリースはmasterとイコールではないので、ズレが生じてしまってる状態です。

1.27.0は今週か来週くらいにリリースされると思います。
今リリース準備中で、致命的なバグが見つかったためにそれを修正してる最中で、それが直って問題なさそうならリリースされます。
https://github.com/serverless/serverless/issues/4923

もし、今どうしてもその機能が必要であれば、`npm install -g serverless/serverless#master`でmasterの最新のものをインストールするやり方があります。

**Comment by sueken5** [comment]
ご回答いただき誠にありがとうございます。とてもためになりました。これかもServerless Frameworkを応援しています！
