### ISSUE TITLE
Unzipped size must be smaller than 262144000 bytes.について

### ISSUE THREAD

**Issue by sueken5** [serverless-japan/forum#7]
度々の質問申し訳ありません。sueken5です。

今回は
```
Unzipped size must be smaller than 262144000 bytes.
```
の質問に参りました。

このようなエラーが出ているので対象となっている関数のコードサイズを確認してみましたところ、以下のように表示されました。

```
$ ls -lh

-rwxr-xr-x  XXXXXXXX  staff   8.0M Apr 28 23:34 XXXXXXXX
```

上記ではコードサイズは「8.0M」でしたのでデプロイ制限にかかってないと思われます。

憶測ではありますが、コードサイズは一関数ごとではなく、デプロイするコードの合計になってしまうのでしょうか？

もしそうであるならば、推奨しているやり方があったりしないでしょうか？

よろしくお願いします。

**Comment by horike37** [comment]
@sueken5 

>度々の質問申し訳ありません。sueken5です。

いえいえ！何度でもwelcomeです！

そのエラーは`serverless deploy`か`serverless deploy function`のどちらを実行されたときのものでしょうか？
前者はCloudFormationで、後者はLambdaのAPIでデプロイするので、どの制限に引っかかるかが変わってきます。

おそらく、https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/limits.html の「デプロイパッケージ (非圧縮 .zip/.jar サイズ) に圧縮できるコード/依存関係のサイズ」の250MBに引っかかってるんじゃないかと思われますが。

その場合は依存パッケージを減らしたり、そのファンクションを複数に分けて軽量化するなど必要になるかと思います。
